


def get_summ(a,b):
    try:
        return int(a) + int(b)

    except ValueError :
        print ("Некорректное значение")
print(get_summ('five',5))




    #try:


    #num_one = int()
    #
    # num_two = int()
    #return sum(num_one, num_tow)

#get_summ(1,2)





#print(sum(num_one, num_tow))
#print(c)


    #except ValueError:
     #   print('Значение аргумента не корректно.')